import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar/index";
import { authUserSession } from "@/libs/auth-libs";
import { UserProvider } from "@/context/userContext";
import ScrollToTop from "@/Components/ScrollTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HS Anime",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/hanime.png", // Ikon default
  //   shortcut: "/hanime.png", // Ikon shortcut (iOS/Android)
  //   apple: "/hanime.png", // Ikon Apple Touch
  // },
};

export default async function RootLayout({ children }) {
  const user = await authUserSession();
  console.log(user);

  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-secondary text-primary`}
      >
        <UserProvider user={user}>
          <Navbar />
          <ScrollToTop />
          <div className="mt-20">{children}</div>
        </UserProvider>
      </body>
    </html>
  );
}
